services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: zenosource
      POSTGRES_PASSWORD: zenosource
      POSTGRES_DB: zenosource
    ports:
      - "5434:5432"
    volumes:
      - zenosource-platform-db:/var/lib/postgresql/data

volumes:
  zenosource-platform-db:
