// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only used by `prisma migrate diff --from-migrations` (which replays the
    // migrations directory into a throwaway database to compare against the
    // schema) and by `migrate dev`. Never touched at runtime. Defaults to a
    // sibling `zenosource_shadow` database on the same local Postgres, so
    // generating a migration doesn't need extra setup — see
    // ../CLAUDE.md#migrations.
    shadowDatabaseUrl:
      process.env["SHADOW_DATABASE_URL"] ??
      process.env["DATABASE_URL"]?.replace(/\/[^/?]+(\?|$)/, "/zenosource_shadow$1"),
  },
});
