import "server-only";
import { db } from "@/lib/db";

export async function getAssignedLocationIds(internalUserId: string): Promise<string[]> {
  const rows = await db.internalUserLocation.findMany({
    where: { internalUserId },
    select: { locationId: true },
  });
  return rows.map((r) => r.locationId);
}

// Undefined = unrestricted (OWNER sees every location). Otherwise, the set
// of location IDs a MEMBER is assigned to and therefore limited to — see
// docs/data-model.md#location.
export async function locationScopeFor(user: {
  id: string;
  role: string;
}): Promise<string[] | undefined> {
  if (user.role === "OWNER") return undefined;
  return getAssignedLocationIds(user.id);
}

// Whether every line-location id in a submitted form actually belongs to
// the caller's tenant — validated the same way createRFQ already validates
// supplier ids ("never trust checkbox/hidden-field values from the form
// directly"). Without this, a crafted request can attach another tenant's
// location to a PO/RFQ line; that location's name then renders on this
// tenant's pages and on the supplier-facing external view, breaching the
// tenant data boundary. Checked before the MEMBER scope check, and for
// every role — a bad id isn't just an out-of-scope one, it may not exist
// in this tenant at all.
export async function allLocationsBelongToTenant(
  locationIds: string[],
  tenantId: string
): Promise<boolean> {
  const unique = [...new Set(locationIds)];
  if (unique.length === 0) return true;
  const found = await db.location.findMany({
    where: { id: { in: unique }, tenantId },
    select: { id: true },
  });
  return found.length === unique.length;
}

// Whether a set of line location ids includes at least one the caller has
// access to — undefined scope means unrestricted (OWNER). Shared by the PO
// and RFQ detail pages/actions so "can this user see or act on this record"
// is one rule, not two copies that can drift.
export function hasLocationAccess(
  lineLocationIds: (string | null | undefined)[],
  scope: string[] | undefined
): boolean {
  if (!scope) return true;
  return lineLocationIds.some((id) => id != null && scope.includes(id));
}

// Picks who should own a new internal ActionItem generated by an external
// action (e.g. a supplier rejecting a PO) — prefer someone assigned to the
// relevant location(s), fall back to any OWNER on the tenant.
export async function pickInternalOwner(
  tenantId: string,
  locationIds: string[]
): Promise<string | null> {
  if (locationIds.length > 0) {
    const assignment = await db.internalUserLocation.findFirst({
      where: { locationId: { in: locationIds }, internalUser: { tenantId } },
      select: { internalUserId: true },
    });
    if (assignment) return assignment.internalUserId;
  }
  const owner = await db.internalUser.findFirst({ where: { tenantId, role: "OWNER" } });
  return owner?.id ?? null;
}
