import "server-only";
import { db } from "@/lib/db";

export async function getAssignedLocationIds(internalUserId: string): Promise<string[]> {
  const rows = await db.internalUserLocation.findMany({
    where: { internalUserId },
    select: { locationId: true },
  });
  return rows.map((r) => r.locationId);
}

// Undefined = unrestricted (OWNER sees every location). Otherwise, the set
// of location IDs a MEMBER is assigned to and therefore limited to — see
// docs/data-model.md#location.
export async function locationScopeFor(user: {
  id: string;
  role: string;
}): Promise<string[] | undefined> {
  if (user.role === "OWNER") return undefined;
  return getAssignedLocationIds(user.id);
}

// Picks who should own a new internal ActionItem generated by an external
// action (e.g. a supplier rejecting a PO) — prefer someone assigned to the
// relevant location(s), fall back to any OWNER on the tenant.
export async function pickInternalOwner(
  tenantId: string,
  locationIds: string[]
): Promise<string | null> {
  if (locationIds.length > 0) {
    const assignment = await db.internalUserLocation.findFirst({
      where: { locationId: { in: locationIds }, internalUser: { tenantId } },
      select: { internalUserId: true },
    });
    if (assignment) return assignment.internalUserId;
  }
  const owner = await db.internalUser.findFirst({ where: { tenantId, role: "OWNER" } });
  return owner?.id ?? null;
}
